class SparseSet:
    def __init__(self, minimum: int, maximum: int) -> None: ...

    @property
    def size(self) -> int: ...

    @property
    def min(self) -> int: ...

    @property
    def max(self) -> int: ...

    def contains(self, value: int) -> bool: ...
    def remove(self, value: int) -> bool: ...
    def values(self) -> list[int]: ...
